# ysmr.toml

hostname="test"

[modules]

    [modules.log]
    enabled=true

        [[modules.log.instance]]
        name="log"
        enabled=true

    [modules.tele]
    enabled=false

        [[modules.tele.instance]]
        name="tele"
        enabled=false
        chat_id=""
        bot_token=""

    [modules.sendgrid]
    enabled=false

        [[modules.sendgrid.instance]]
        name="sendgrid"
        enabled=false
        account_sid = ""
        auth_token = ""
        sender = ""
        recipient = ""

    [modules.smtp]
    enabled=false

        [[modules.smtp.instance]]
        name="smtp"
        enabled=false
        server = ""
        port = ""
        login = ""
        secret = ""
        recipient = ""
        sender = ""

    [modules.mongo]
    enabled=false

        [[modules.mongo.instance]]
        name="mongo"
        enabled=false
        url=""
        db=""
        collection=""
