# ysmr.toml

hostname="test"

[[module]]
name="log"
enabled=true

    [[module.instance]]
    name="log1"
    enabled=true

[[module]]
name="tele1"
enabled=false

    [[module.instance]]
    name="tele1"
    enabled=false
    chat_id=""
    bot_token=""

[[module]]
name="sendgrid"
enabled=false

    [[module.instance]]
    name="sendgrid1"
    enabled=false
    account_sid = ""
    auth_token = ""
    sender = ""
    recipient = ""

[[module]]
name="smtp"
enabled=false

    [[module.instance]]
    name="smtp1"
    enabled=false
    server = ""
    port = ""
    login = ""
    secret = ""
    recipient = ""
    sender = ""

[[module]]
name="mongo"
enabled=false

    [[module.instance]]
    name="mongo1"
    enabled=false
    url=""
    db=""
    collection=""
