# ysmr.toml

# Define module instances here

[[module]]
name="log"
enabled="true"

[[module]]
name="tele"
enabled=false
chat_id=""
bot_token=""

[[module]]
name="sendgrid"
enabled=false
account_sid = ""
auth_token = ""
sender = ""
recipient = ""

[[module]]
name="smtp"
enabled=true
server = ""
port = ""
login = ""
secret = ""
recipient = ""
sender = ""