# ysmr.toml

[[module]]
name="log"
enabled="true"

[[module]]
name="tele"
enabled=false
chat_id=""
bot_token=""

[[module]]
name="sendgrid"
enabled="false"
account_sid = ""
auth_token = ""
from = ""
to = ""

[[module]]
name="smtp"
enabled="false"
server = ""
port = ""
login = ""
secret = ""
to = ""
from = ""